application: love-pie
version: 1
runtime: java

handlers:
- url: /
  servlet: lovep.ie.Landing

- url: /charity/*
  servlet: lovep.ie.CharityServlet

- url: /donate/*
  servlet: lovep.ie.servlet.Donate